protected/models/Content.php
<?php

/**
 * This is the model class for table "tbl_content".
 *
 * The followings are the available columns in table 'tbl_content':
 * @property integer $id
 * @property string $page_title
 * @property integer $user_id
 * @property integer $published
 * @property string $type
 * @property string $body
 * @property string $picture1
 * @property string $picture2
 * @property string $picture3
 * @property string $pub_date
 * @property string $created_on
 * @property string $updated_on
 */
class Content extends CActiveRecord
{
	public $uploadedCover;
	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Content the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{content}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('page_title, published, type, body, pub_date', 'required'),
			array('user_id, published, vote', 'numerical', 'integerOnly'=>true),
			array('picture1, picture2, picture3', 'length', 'max'=>100),
			array('uploadedCover', 'file', 'types'=>'jpg, jpeg, gif, png', 'allowEmpty'=>true, 'safe'=>true),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, page_title, user_id, published, type, body, pub_date, created_on, updated_on', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'comments' => array(self::HAS_MANY, 'Comment', 'content_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'categories' => array(self::MANY_MANY, 'Tag',
							'tbl_tag_content(content_id, tag_id)'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'page_title' => 'Page Title',
			'user_id' => 'User',
			'published' => 'Published',
			'type' => 'Type',
			'body' => 'Body',
			'cover' => 'Cover',
			'picture1' => 'Picture1',
			'picture2' => 'Picture2',
			'picture3' => 'Picture3',
			'pub_date' => 'Pub Date',
			'created_on' => 'Created On',
			'updated_on' => 'Updated On',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('page_title',$this->page_title,true);
		$criteria->compare('user_id',$this->user_id);
		$criteria->compare('published',$this->published);
		$criteria->compare('type',$this->type,true);
		$criteria->compare('body',$this->body,true);
		$criteria->compare('cover',$this->cover,true);
		$criteria->compare('pub_date',$this->pub_date,true);
		$criteria->compare('created_on',$this->created_on,true);
		$criteria->compare('updated_on',$this->updated_on,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	/**
	 * We're overriding this method to fill findAll() and similar method result
	 * with proper models.
	 *
	 * @param array $attributes
	 * @return Content
	 */
	protected function instantiate($attributes)
	{
		switch($attributes['type']){
			case 'content':
				$class = get_class($this);;
				break;
			default:
				$class = 'Review';
		}
		$model = new $class(null);
		return $model;
	}
	
	/* removed to allow reviews on home page
	function defaultScope(){
		return array(
			'condition'=>"type='content'",
		);
	}
	*/
	
	public function scopes()
	{
		return array(
			'sitemap'=>array('condition'=>'pub_date <= NOW()', 'order'=>'created_on DESC'),
		);
	}
	
	public function addComment($comment)
	{
		$comment->content_id=$this->id;
		return $comment->save();
	}
	
	protected function beforeSave()
	{
		if(parent::beforeSave()) {
			if ($this->isNewRecord)
				$this->created_on = new CDbExpression('NOW()');
			else
				$this->updated_on = new CDbExpression('NOW()');
			
			$this->user_id = 1;
		
			if (is_object($this->uploadedCover) && get_class($this->uploadedCover)==='CUploadedFile')
				$this->cover = $this->uploadedCover->getName();
		
			return true;
		}
		
		return false;
	}
	
	public function behaviors()
	{
		return array( 'CAdvancedArBehavior' => array(
				'class' => 'application.extensions.CAdvancedArBehavior'));
	}
	
	public function urlifyTitle() 
	{
    	$result = $this->page_title;
    	$result = strtolower($result);
    	$result = preg_replace('/[^\w\d_ ]/si', '', $result);
    	$result = preg_replace('/\s+/', '-', $result);
    	return $result;
    }
    
    public function getUrlifiedTitle()
    {
    	return $this->urlifyTitle();
    }
        
    public function getUrl($absolute=false) {
    	if ($absolute) {
    		if ($this->type == 'content')
    			return Yii::app()->createAbsoluteUrl('content/view', array('id' => $this->id, 'title'=>$this->urlifyTitle()));
    		else
    			return Yii::app()->createAbsoluteUrl('review/view', array('id' => $this->id, 'title'=>$this->urlifyTitle()));
    	} else {
	    	if ($this->type == 'content')
	    		return Yii::app()->createUrl('content/view', array('id' => $this->id, 'title'=>$this->urlifyTitle()));
	    	else
	    		return Yii::app()->createUrl('review/view', array('id' => $this->id, 'title'=>$this->urlifyTitle()));
    	}
    }
    
    /**
     *  @TODO: remove '/20mins on production'
     */
    public function getCoverUrl()
    {
    	return '/20mins' . Yii::app()->params['coversPath'] . (is_null($this->cover) ? 'default.jpg' : $this->cover);
    }
    
    public function getTeaser($chars, $trailing = '[...]') 
    {
    	$text = $this->body;
    	if (strlen($this->body) > $chars) {
    		$text = strip_tags($this->body);
    		$text = substr($text, 0, $chars);
    		$text = substr($text, 0, strrpos($text," "));
    		$text = str_replace('<p>', '', $text);
    		$text = str_replace('</p>', '', $text);
    		$text = '<p>' . $text . ' ' . $trailing . '</p>';
    	}
    	return $text;
    }
    
    public function getCategory()
    {
    	return 'Blog';
    }
}

protected/controllers/TagController.php
<?php

class TagController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Tag;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Tag']))
		{
			$model->attributes=$_POST['Tag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Tag']))
		{
			$model->attributes=$_POST['Tag'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Tag');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Tag('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Tag']))
			$model->attributes=$_GET['Tag'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Tag the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Tag::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Tag $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='tag-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/content/_commentForm.php
<?php
/* @var $this CommentController */
/* @var $model Comment */
/* @var $form CActiveForm */
?>

<div class="comment-form">
	
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'comment-form',
	'action' => Yii::app()->request->url,
	'enableAjaxValidation'=>true,
)); ?>
	
	<h5>Lascia un Commento</h5>
	
	<p class="note">I campi con <span class="required">*</span> Sono obbligatori.</p>

	<?php //echo $form->errorSummary($comment, array('class'=>'alert error')); ?>

	<div class="input-box">
		<?php echo $form->labelEx($comment,'author'); ?>
		<?php echo $form->textField($comment,'author',array('size'=>50,'maxlength'=>50)); ?>
		<?php echo $form->error($comment,'author'); ?>
	</div>

	<div class="input-box">
		<?php echo $form->labelEx($comment,'email'); ?>
		<?php echo $form->textField($comment,'email',array('size'=>60,'maxlength'=>80)); ?>
		<?php echo $form->error($comment,'email'); ?>
	</div>
	
	<div class="clearfix"></div>
	
	<div class="input-box area">
		<?php echo $form->labelEx($comment,'body'); ?>
		<?php echo $form->textArea($comment,'body',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($comment,'body'); ?>
	</div>
	
	<div class="clearfix"></div>
	
	<?php echo CHtml::submitButton('Send', array('class'=>'button')); ?>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/content/_form.php
<?php
/* @var $this ContentController */
/* @var $model Content */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'content-form',
	'enableAjaxValidation'=>true,
	'htmlOptions'=>array('enctype'=>'multipart/form-data'),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'page_title'); ?>
		<?php echo $form->textField($model,'page_title',array('size'=>60,'maxlength'=>200)); ?>
		<?php echo $form->error($model,'page_title'); ?>
	</div>

	<div class="row">
		<?php echo $form->hiddenField($model,'type',array('value'=>'content'));?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'body'); ?>
		<?php $this->widget('application.extensions.tinymce.ETinyMce', array('model'=>$model, 'attribute'=>'body')); ?>
		<?php echo $form->error($model,'body'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'cover'); ?>
		<?php echo $form->textField($model,'cover',array('size'=>50,'maxlength'=>50,'readonly'=>'true','disabled'=>'true')); ?>
		<?php echo $form->error($model,'cover'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'uploadedCover'); ?>
		<?php echo $form->fileField($model,'uploadedCover'); ?>
		<?php echo $form->error($model,'uploadedCover'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'published'); ?>
		<?php echo $form->checkBox($model, 'published', array('checked'=>'checked')); ?>
		<?php echo $form->error($model,'published'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'pub_date'); ?>
		<?php echo $form->textField($model,'pub_date', array('value' => date("Y-m-d H:i:s"))); ?>
		<?php echo $form->error($model,'pub_date'); ?>
	</div>
	
	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/content/_search.php
<?php
/* @var $this ContentController */
/* @var $model Content */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'page_title'); ?>
		<?php echo $form->textField($model,'page_title',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'published'); ?>
		<?php echo $form->textField($model,'published'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'type'); ?>
		<?php echo $form->textField($model,'type',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'body'); ?>
		<?php echo $form->textArea($model,'body',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'cover'); ?>
		<?php echo $form->textField($model,'cover',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'picture1'); ?>
		<?php echo $form->textField($model,'picture1',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'picture2'); ?>
		<?php echo $form->textField($model,'picture2',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'picture3'); ?>
		<?php echo $form->textField($model,'picture3',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'italian_title'); ?>
		<?php echo $form->textField($model,'italian_title',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'italian_subtitle'); ?>
		<?php echo $form->textField($model,'italian_subtitle',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'original_title'); ?>
		<?php echo $form->textField($model,'original_title',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'original_subtitle'); ?>
		<?php echo $form->textField($model,'original_subtitle',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'year'); ?>
		<?php echo $form->textField($model,'year',array('size'=>4,'maxlength'=>4)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'vote'); ?>
		<?php echo $form->textField($model,'vote'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'author_id'); ?>
		<?php echo $form->textField($model,'author_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'actors'); ?>
		<?php echo $form->textArea($model,'actors',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nation'); ?>
		<?php echo $form->textField($model,'nation',array('size'=>30,'maxlength'=>30)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pages'); ?>
		<?php echo $form->textField($model,'pages',array('size'=>5,'maxlength'=>5)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'editor'); ?>
		<?php echo $form->textField($model,'editor',array('size'=>50,'maxlength'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'language'); ?>
		<?php echo $form->textField($model,'language',array('size'=>20,'maxlength'=>20)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'seasons'); ?>
		<?php echo $form->textField($model,'seasons',array('size'=>60,'maxlength'=>200)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pub_date'); ?>
		<?php echo $form->textField($model,'pub_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created_on'); ?>
		<?php echo $form->textField($model,'created_on'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated_on'); ?>
		<?php echo $form->textField($model,'updated_on'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/content/_tagsForm.php
<?php
/* @var $this ContentController */
/* @var $model Content */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'content-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>
	
	<div class="row">
		<?php echo $form->labelEx($model,'tags'); ?>
		<?php //echo $form->checkBoxList($model, 'tagIds', Chtml::listData(Tag::model()->findAll(array('order'=>'name')),'id','name'));  ?>
		<?php echo CHtml::checkBoxList(
							'Content[categories]',
							array_map(create_function('$o', 'return $o->id;'), $model->categories), 
							Chtml::listData(Tag::model()->findAll(array('order'=>'name')),'id','name')
		); ?>
		<?php echo $form->error($model,'tags'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/content/_view.php
<?php
/* @var $this ContentController */
/* @var $data Content */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('page_title')); ?>:</b>
	<?php echo CHtml::encode($data->page_title); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode(User::model()->findByPk($data->user_id)->username); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('published')); ?>:</b>
	<?php echo CHtml::encode($data->published); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('type')); ?>:</b>
	<?php echo CHtml::encode($data->type); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('cover')); ?>:</b>
	<?php echo CHtml::encode($data->cover); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('pub_date')); ?>:</b>
	<?php echo CHtml::encode($data->pub_date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('created_on')); ?>:</b>
	<?php echo CHtml::encode($data->created_on); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('updated_on')); ?>:</b>
	<?php echo CHtml::encode($data->updated_on); ?>
	<br />

</div>

protected/views/content/admin.php
<?php
/* @var $this ContentController */
/* @var $model Content */

$this->breadcrumbs=array(
	'Contents'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Content', 'url'=>array('index')),
	array('label'=>'Create Content', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#content-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Contents</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'content-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'page_title',
		'published',
		'type',
		'pub_date',
		array(
		'class'=>'CButtonColumn',
		'htmlOptions' => array('width'=>'70px'),
		'template'=>'{tag}{update}{delete}{view}',
		'buttons'=>array(
				'tag' => array
				(
						'label'=>'Choose tags for this review',
						'imageUrl'=>Yii::app()->request->baseUrl.'/images/tag.png',
						'url'=>'Yii::app()->createUrl("content/tag", array("id" => $data->id))',
				),
		),
),
	),
)); ?>

protected/views/content/create.php
<?php
/* @var $this ContentController */
/* @var $model Content */

$this->breadcrumbs=array(
	'Contents'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Content', 'url'=>array('index')),
	array('label'=>'Manage Content', 'url'=>array('admin')),
);
?>

<h1>Create Content</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/content/index.php
<?php
/* @var $this ContentController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Contents',
);

$this->menu=array(
	array('label'=>'Create Content', 'url'=>array('create')),
	array('label'=>'Manage Content', 'url'=>array('admin')),
);
?>

<h1>Contents</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/content/list.php
			<?php
			$this->setPageTitle($this->title.' - '.Yii::app()->name); 
			$this->subtitle='Elenco di post';
			?>
			
			<div class="eleven columns">
				<?php foreach ($contents as $content) { ?>
				<div class="blog-post">
					<div class="date">
						<span class="month"><?php echo strtoupper(date('M', strtotime($content->pub_date))); ?></span>
						<span class="day-year"><?php echo date('jS', strtotime($content->pub_date)) . ', ' . date('Y', strtotime($content->pub_date)); ?></span>
					</div>
					<div class="post">
						<div class="image-container">
							<img src="<?php echo $content->getCoverUrl(); ?>" alt="" />
							<div class="blog-read-more"></div>
						</div>
						<div class="meta">
								<ul>
									<li><i class="icon-tasks"></i> Categoria: <span><a href="javascript:void(0)"><?php echo $content->getCategory(); ?></a></span></li>
									<li><i class="icon-tag"></i> Tags: 
										<span>
											<?php 
												$tagsarray = array();
												foreach ($content->categories as $tag) {
													$tagsarray[] = CHtml::link(ucfirst($tag->name), Yii::app()->createUrl('tag/view', array('tagId' => $tag->id, 'tag'=>$tag->urlifyTagName()))); 
												}
												$tagsHtml = implode(', ', $tagsarray);
												echo $tagsHtml;
											?>
										</span>
									</li>
									<li><i class="icon-comments"></i> Commenti: <span><a href="javascript:void(0)"><?php echo count($content->comments); ?></a></span></li>
								</ul>
						</div>
						<h3><?php echo CHtml::link($content->page_title, Yii::app()->createUrl(($content->type == 'content') ? 'content/view' : 'review/view', array('id' => $content->id, 'title'=>$content->urlifyTitle()))); ?></h3>
						<?php echo $content->getTeaser(200); ?>
						<?php echo CHtml::link('Leggi tutto', Yii::app()->createUrl(($content->type == 'content') ? 'content/view' : 'review/view', array('id' => $content->id, 'title'=>$content->urlifyTitle())), array('class'=>'button')); ?>
					</div>
					<div class="clearfix"></div>
				</div>
				<?php } ?>
				
				<?php // display pagination ?>
				<?php $this->widget('CustomPager', array(
						'pages' => $pages,
						'currentPage'=>$pages->getCurrentPage(),
						'itemCount'=>$pages->itemCount,
						'id'=>'pagination',
						'hiddenPageCssClass'=>'disabled_pagination',
						'selectedPageCssClass'=>'active_link',
						'nextPageLabel'=>'&gt;&gt;',
						'prevPageLabel'=>'&lt;&lt;',
						'pageSize'=>Yii::app()->params['pageSize'],
				)) ?>
			</div>